# Generated by Django 5.1.3 on 2024-12-26 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('offer_management', '0002_offer'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='productvariant',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('category', 'Category'), ('product', 'Product')], max_length=10),
        ),
    ]
