# Generated by Django 5.1.3 on 2025-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0003_remove_offer_productvariant_offer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
