# Generated by Django 5.1.3 on 2025-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0004_offer_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
