# Generated by Django 5.1.3 on 2025-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0005_coupon_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
