# Generated by Django 5.1.3 on 2025-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
