# Generated by Django 5.1.3 on 2024-12-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_refund_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_amount',
        ),
    ]
