# Generated by Django 5.1.3 on 2024-12-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizing_issues', models.BooleanField(default=False)),
                ('damaged_item', models.BooleanField(default=False)),
                ('incorrect_order', models.BooleanField(default=False)),
                ('delivery_delays', models.BooleanField(default=False)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_reasons', to='orders.order')),
            ],
        ),
    ]
