# Generated by Django 5.1.3 on 2025-01-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizing_issues', models.BooleanField(default=False)),
                ('damaged_item', models.BooleanField(default=False)),
                ('incorrect_order', models.BooleanField(default=False)),
                ('delivery_delays', models.BooleanField(default=False)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_return', to='orders.orderitem')),
            ],
        ),
    ]
