# Generated by Django 5.1.3 on 2025-01-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitemreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('PAYMENT_PENDING', 'Payment Pending')], default='PENDING', max_length=20),
        ),
    ]
